# Generated by Django 5.2 on 2025-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('telegramUser', models.CharField(max_length=50, verbose_name='Telegram username')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
            ],
        ),
    ]
