# Generated by Django 5.2 on 2025-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_technology_projects_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Описание'),
        ),
    ]
