# Generated by Django 5.2 on 2025-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание'),
        ),
    ]
