# Generated by Django 5.2 on 2025-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
