# Generated by Django 5.2 on 2025-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_skills_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='skills',
            name='level_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='skills',
            name='level_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='skills',
            name='level_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Уровень'),
        ),
    ]
