# Generated by Django 5.2 on 2025-08-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects_description_en_projects_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
