# Generated by Django 5.2 on 2025-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projects_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='month',
            field=models.CharField(default='', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='year',
            field=models.CharField(default='', verbose_name='Год'),
        ),
    ]
